#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { freshPersistentState } from '../src/stoneage_persistent_state.mjs';
import { NPC_DISPATCH_RUNTIME_FORMAT, resolveInteractionModule, dispatchNpcInteraction } from '../src/stoneage_npc_dispatch_runtime.mjs';
import { createFirstRouteRewardHandlers } from '../src/stoneage_first_route_reward_handlers.mjs';
import { createAuditedNpcModuleRegistry } from '../src/stoneage_npc_module_registry_runtime.mjs';
const reachability=JSON.parse(fs.readFileSync('data/generated/stoneage_start_npc_reachability.json','utf8'));
const closure=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_event_closure.json','utf8'));
const itemRewardCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_item_reward_runtime.json','utf8'));
const itemMakeCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_item_make_runtime.json','utf8'));
const petCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_pet_runtime.json','utf8'));
const audit=JSON.parse(fs.readFileSync('data/generated/stoneage_world_npc_functionset_audit.json','utf8'));
assert.equal(NPC_DISPATCH_RUNTIME_FORMAT,'stoneage-npc-dispatch-runtime-v1');
const changeevent=reachability.rows.find(r=>r.template==='changeevent'&&r.hometown===0); assert.ok(changeevent);
const registry=createAuditedNpcModuleRegistry(audit,{modules:{ExChangeMan:{script:closure.script,kind:'changeevent-source-resolved'}}});
const resolved=resolveInteractionModule(changeevent,{moduleRegistry:registry});
assert.equal(resolved.resolved,true); assert.equal(resolved.sourceBackedTemplate,true); assert.equal(resolved.compatibilityAlias,false); assert.equal(resolved.functionset,'ExChangeMan');
const bundle=createFirstRouteRewardHandlers({itemRewardCatalog,itemMakeCatalog,petCatalog,petIdFactory:(st,created)=>'pet-'+created.petId,itemCapacity:1000,itemCursor:500,randInclusive:(a,b)=>a===b?a:0});
const state=freshPersistentState({playerId:'dispatch-changeevent'}); state.player.level=1; state.player.transmigration=0; state.player.charm=60;
const executed=await dispatchNpcInteraction(state,changeevent,{floor:1006,x:15,y:21,facingCell:[1006,15,22]},{interactionRule:'NPC_Util_charIsInFrontOfChar distance=1',moduleRegistry:registry,handlerFactory:()=>bundle.handlers,transactionId:'dispatch-changeevent-1',now:()=> '2026-09-30T09:00:00.000Z'});
assert.equal(executed.ok,true); assert.equal(executed.handled,true); assert.equal(executed.execution.applied,true); assert.equal(executed.state.revision,1); assert.equal(executed.state.inventory.itemRuntime.slots['500'].itemId,20145); assert.equal(executed.state.pets.petBox[0].petId,274);
console.log(JSON.stringify({pass:true,format:NPC_DISPATCH_RUNTIME_FORMAT,changeeventSourceResolved:true,strictSourceDispatchExecutes:true,savedRevision:executed.state.revision,savedItem:20145,savedPetTempNo:274}));
