#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { freshPersistentState } from '../src/stoneage_persistent_state.mjs';
import { createBrowserStateController } from '../src/stoneage_browser_state_controller.mjs';
import { createBrowserIdleBattleStrategyRuntime } from '../src/stoneage_browser_idle_battle_strategy_runtime.mjs';
import { createBrowserBattleEnemyAiRuntime } from '../src/stoneage_browser_battle_enemy_ai_runtime.mjs';
import { createBrowserBattleRoundRuntime } from '../src/stoneage_browser_battle_round_runtime.mjs';
import { createBrowserBattleAttackCountRuntime } from '../src/stoneage_browser_battle_attack_count_runtime.mjs';
import { createBrowserBattleTargetListRuntime } from '../src/stoneage_browser_battle_target_list_runtime.mjs';
import { createBrowserBattleAttackSequenceRuntime } from '../src/stoneage_browser_battle_attack_sequence_runtime.mjs';
import { createBrowserBattleCounterChainRuntime } from '../src/stoneage_browser_battle_counter_chain_runtime.mjs';
import { createBrowserBattleCounterRuntime } from '../src/stoneage_browser_battle_counter_runtime.mjs';
import { createBrowserBattleAttackPreflightRuntime } from '../src/stoneage_browser_battle_attack_preflight_runtime.mjs';
import { createBrowserBattleAttackSeqPreludeRuntime } from '../src/stoneage_browser_battle_attack_seq_prelude_runtime.mjs';
import { createBrowserBattleDamagePlanRuntime } from '../src/stoneage_browser_battle_damage_plan_runtime.mjs';
import { createBrowserBattleCriticalDamageRuntime } from '../src/stoneage_browser_battle_critical_damage_runtime.mjs';
import { createBrowserBattleDamageReactRuntime } from '../src/stoneage_browser_battle_damage_react_runtime.mjs';
import { createBrowserBattleDamageReactCommitRuntime } from '../src/stoneage_browser_battle_damage_react_commit_runtime.mjs';
import { createBrowserBattleDamageDeathChainRuntime } from '../src/stoneage_browser_battle_damage_death_chain_runtime.mjs';
import { createBrowserBattleProfitCreditRuntime } from '../src/stoneage_browser_battle_profit_credit_runtime.mjs';
import { createBrowserBattleCarriedLootRuntime } from '../src/stoneage_browser_battle_carried_loot_runtime.mjs';
import { createBrowserBattleEnemyExpRuntime } from '../src/stoneage_browser_battle_enemy_exp_runtime.mjs';
import { createBrowserBattleRelifeRuntime } from '../src/stoneage_browser_battle_relife_runtime.mjs';
import { createBrowserBattleRidePetAdjustRuntime } from '../src/stoneage_browser_battle_ride_pet_adjust_runtime.mjs';
import { createBrowserBattleDexRuntime } from '../src/stoneage_browser_battle_dex_runtime.mjs';
import { createBrowserBattleStatusRuntime } from '../src/stoneage_browser_battle_status_runtime.mjs';
import { createBrowserBattleEndRuntime } from '../src/stoneage_browser_battle_end_runtime.mjs';
import { ACTION_WORLD_ENCOUNTER_GROUP_SELECT,ACTION_WORLD_ENCOUNTER_ENEMY_GENERATE,ACTION_ENCOUNTER_BATTLE_CONTEXT_BUILD,ACTION_BATTLE_INITIALIZE } from '../src/stoneage_browser_state_controller.mjs';
import { createBrowserBattleAutoRuntime } from '../src/stoneage_browser_battle_auto_runtime.mjs';
const routeCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_first_idle_route_catalog.json','utf8'));
const encounterIndex=JSON.parse(fs.readFileSync('data/generated/stoneage_start_encounter_target_index.json','utf8'));
const groupCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_start_encounter_group_runtime.json','utf8'));
const relifeCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_item_relife_runtime.json','utf8'));
const state=freshPersistentState({playerId:'v467-auto',playerName:'V4.67'});
state.player.hp=1000;state.player.maxHp=1000;state.player.mp=100;state.player.maxMp=100;state.player.stats={str:100,dex:100,tgh:100,vital:100};state.idle.enabled=true;state.idle.mode='encounter_pending';state.idle.routeId='hometown-0/floor-1000-to-100/1000_to_100_a';state.world.position={floorId:100,x:610,y:538};
const controller=createBrowserStateController({state,idleRouteCatalog:routeCatalog,encounterTargetIndex:encounterIndex,encounterGroupCatalog:groupCatalog,battleFieldNoProvider:0,playerRelifeCatalog:relifeCatalog});
const encounter={encounterId:65,floorId:100,x:610,y:538};
const selected=await controller.dispatch({type:ACTION_WORLD_ENCOUNTER_GROUP_SELECT,encounter,groupRoll:2});assert.equal(selected.ok,true,JSON.stringify(selected));
const statRolls=[{levelRoll:0,baseStatRolls:[2,2,2,2],allocationRolls:Array(10).fill(0)},{levelRoll:0,baseStatRolls:[2,2,2,2],allocationRolls:Array(10).fill(0)}];
const generated=await controller.dispatch({type:ACTION_WORLD_ENCOUNTER_ENEMY_GENERATE,encounter,groupId:94,entryMaxRoll:2,enemyRolls:[0,1],enemyStatRolls:statRolls});assert.equal(generated.ok,true,JSON.stringify(generated));
const built=await controller.dispatch({type:ACTION_ENCOUNTER_BATTLE_CONTEXT_BUILD,encounter,groupId:94,battleFieldNo:0,enemyTeam:generated.team,materializeEnemyStats:true});assert.equal(built.ok,true,JSON.stringify(built));
const initialized=await controller.dispatch({type:ACTION_BATTLE_INITIALIZE,fixedLuck:0,surpriseRoll:100});assert.equal(initialized.ok,true,JSON.stringify(initialized));
const profitCreditRuntime=createBrowserBattleProfitCreditRuntime(),carriedLootRuntime=createBrowserBattleCarriedLootRuntime(),enemyExpRuntime=createBrowserBattleEnemyExpRuntime(),relifeRuntime=createBrowserBattleRelifeRuntime();
const attackCountRuntime=createBrowserBattleAttackCountRuntime(),targetListRuntime=createBrowserBattleTargetListRuntime(),counterRuntime=createBrowserBattleCounterRuntime(),attackPreflightRuntime=createBrowserBattleAttackPreflightRuntime(),attackSeqPreludeRuntime=createBrowserBattleAttackSeqPreludeRuntime();
const damagePlanRuntime=createBrowserBattleDamagePlanRuntime(),criticalDamageRuntime=createBrowserBattleCriticalDamageRuntime(),damageReactRuntime=createBrowserBattleDamageReactRuntime(),damageReactCommitRuntime=createBrowserBattleDamageReactCommitRuntime(),damageDeathChainRuntime=createBrowserBattleDamageDeathChainRuntime(),ridePetAdjustRuntime=createBrowserBattleRidePetAdjustRuntime(),dexRuntime=createBrowserBattleDexRuntime(),statusRuntime=createBrowserBattleStatusRuntime(),endRuntime=createBrowserBattleEndRuntime();
const attackSequenceRuntime=createBrowserBattleAttackSequenceRuntime({attackPreflightRuntime,attackSeqPreludeRuntime,damagePlanRuntime,criticalDamageRuntime,damageReactRuntime,damageReactCommitRuntime,damageDeathChainRuntime,profitCreditRuntime,carriedLootRuntime,enemyExpRuntime,ridePetAdjustRuntime,relifeRuntime});
const counterChainRuntime=createBrowserBattleCounterChainRuntime({counterRuntime,profitCreditRuntime,carriedLootRuntime,enemyExpRuntime,ridePetAdjustRuntime,attackSeqPreludeRuntime,damagePlanRuntime,criticalDamageRuntime,damageReactRuntime,damageReactCommitRuntime,damageDeathChainRuntime,relifeRuntime});
const roundRuntime=createBrowserBattleRoundRuntime({attackCountRuntime,targetListRuntime,attackSequenceRuntime,ridePetAdjustRuntime,dexRuntime,attackPreflightRuntime,attackSeqPreludeRuntime,damagePlanRuntime,criticalDamageRuntime,damageReactRuntime,damageReactCommitRuntime,damageDeathChainRuntime,counterChainRuntime,statusRuntime,endRuntime,profitCreditRuntime,carriedLootRuntime,enemyExpRuntime,relifeRuntime});
const auto=createBrowserBattleAutoRuntime({playerStrategyRuntime:createBrowserIdleBattleStrategyRuntime(),enemyAiRuntime:createBrowserBattleEnemyAiRuntime(),roundRuntime});assert.equal(auto.ok,true);
const bundle={weaponType:'none',weaponCritical:0,throwWeapon:false,duckRoll:10000,criticalRoll:10000,damageRollNear:1,damageRollWide:1,guardRoll:96,lowDamageRoll:1,battleDamageModify:1,includeAttr:false,defaultTargetRoll:0};
const result=await auto.run(initialized.battleContext,{playerId:state.player.id,maxRounds:1,rounds:[{defaultTargetRoll:0,enemyActionRolls:[0],enemyTargetRolls:[0],roundOptions:{attackRolls:[{attackerBid:0,...bundle},{attackerBid:10,...bundle}],counterPolicy:'defer',weaponClassByBid:{0:'none',10:'none'}}}]});
assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.roundsExecuted,1);assert.equal(result.history[0].strategy.command.code,1);assert.equal(result.history[0].enemyAi.commands[0].commandCode,1);assert.equal(result.history[0].round.stage,'battle-round-resolved');assert.equal(result.context.turn,1);assert.equal(result.persistentMutation,false);assert.equal(result.rngGeneratedInternally,false);
const noRounds=await auto.run(initialized.battleContext,{playerId:state.player.id,maxRounds:1,rounds:[{}]});assert.equal(noRounds.ok,false);assert.equal(noRounds.reason,'battle-auto-round-inputs-insufficient');
console.log(JSON.stringify({pass:true,format:'stoneage-v467-browser-battle-auto-orchestrator-v1',roundsExecuted:result.roundsExecuted,strategyApplied:true,enemyAiApplied:true,roundResolved:true,finished:result.finished,persistentMutation:result.persistentMutation,rngGeneratedInternally:result.rngGeneratedInternally},null,2));