#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { freshPersistentState } from '../src/stoneage_persistent_state.mjs';
import { createFirstRouteRewardHandlers } from '../src/stoneage_first_route_reward_handlers.mjs';
import { createAuditedNpcModuleRegistry, resolveAuditedNpcModule } from '../src/stoneage_npc_module_registry_runtime.mjs';
import { dispatchNpcInteraction } from '../src/stoneage_npc_dispatch_runtime.mjs';
const audit=JSON.parse(fs.readFileSync('data/generated/stoneage_world_npc_functionset_audit.json','utf8'));
const changeAudit=JSON.parse(fs.readFileSync('data/generated/stoneage_changeevent_module_audit.json','utf8'));
const reach=JSON.parse(fs.readFileSync('data/generated/stoneage_start_npc_reachability.json','utf8'));
const closure=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_event_closure.json','utf8'));
assert.equal(audit.fixedSource.ref,'1f90cb6cb57c1df70f39cde77a5a8ccd98b66c56');
assert.deepEqual(audit.sourceTemplateBindings[0],{templateName:'changeevent',normalizedTemplateName:'changeevent',functionset:'ExChangeMan',normalizedFunctionSet:'exchangeman',sourcePath:'gmsv/data/npc/jaruga/event/event.template',sourceBlobSha:'99ed9d950cd1ee4d59726a07dc6f50d9d78fa423',makeAtNoBody:1,makeAtNoSee:1,graphicName:0});
assert.equal(changeAudit.status,'runtime-module-resolved');
assert.equal(changeAudit.pinnedTemplate.functionset,'ExChangeMan');
assert.equal(changeAudit.pinnedModule.functionset,'ExChangeMan');
const rows=reach.rows.filter(r=>r.template==='changeevent');
assert.equal(rows.length,5); assert.equal(rows.every(r=>r.reachableInteraction===true),true); assert.equal(rows.every(r=>r.runtimeModuleStatus==='source_resolved_in_pinned_template_functionSet'),true);
assert.equal(reach.statistics.templateModuleUnresolvedInstances,0);
assert.equal(closure.owner.runtimeModuleStatus,'resolved_in_pinned_template_functionSet');
assert.equal(closure.semantics.ownerClosed,true); assert.equal(closure.semantics.runtimeModuleClosed,true);
const registry=createAuditedNpcModuleRegistry(audit,{modules:{ExChangeMan:{script:closure.script,kind:'changeevent-source-resolved'}}});
const resolved=resolveAuditedNpcModule(registry,'changeevent');
assert.equal(resolved.resolved,true); assert.equal(resolved.sourceBackedTemplate,true); assert.equal(resolved.compatibilityAlias,false); assert.equal(resolved.functionset,'ExChangeMan');
const bundle=createFirstRouteRewardHandlers({itemRewardCatalog:JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_item_reward_runtime.json','utf8')),itemMakeCatalog:JSON.parse(fs.readFileSync('data/generated/stoneage_item_make_runtime.json','utf8')),petCatalog:JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_pet_runtime.json','utf8')),petIdFactory:(st,created)=>'pet-'+created.petId,itemCapacity:1000,itemCursor:900,randInclusive:(a,b)=>a===b?a:0});
const state=freshPersistentState({playerId:'v364-changeevent'}); state.player.level=1; state.player.transmigration=0; state.player.charm=60;
const npc=rows.find(r=>r.hometown===0&&r.floor===1006&&r.blockIndex===2);
const result=await dispatchNpcInteraction(state,npc,{floor:1006,x:15,y:21,facingCell:[1006,15,22]},{interactionRule:'NPC_Util_charIsInFrontOfChar distance=1',moduleRegistry:registry,handlerFactory:()=>bundle.handlers,transactionId:'v364-1',now:()=> '2026-09-30T18:30:00.000Z'});
assert.equal(result.ok,true); assert.equal(result.handled,true); assert.equal(result.execution.applied,true); assert.equal(result.state.revision,1); assert.equal(result.state.inventory.itemRuntime.slots['900'].itemId,20145); assert.equal(result.state.pets.petBox[0].petId,274); assert.equal(result.state.events.endWords[11],16384);
console.log(JSON.stringify({pass:true,format:'stoneage-changeevent-source-resolution-v1',pinnedTemplate:'changeevent',functionset:'ExChangeMan',startFloorInstances:rows.length,strictSourceDispatch:true,compatibilityAliasRequired:false,savedRevision:result.state.revision},null,2));
