import assert from 'node:assert/strict';
import fs from 'node:fs';
import {sourceMapImageAttributes,sourceMapTileWithAttributes} from '../src/stoneage_map_runtime.mjs';
const mapset=JSON.parse(fs.readFileSync('data/generated/stoneage_mapset_runtime.json','utf8'));
assert.equal(mapset.version,'V3.13');
assert.equal(mapset.imageCount,20166);
assert.equal(mapset.maxImageId,41000);
assert.deepEqual(mapset.haveHeightImageIds,[1,3,5,7,9,11]);
assert.equal(mapset.walkableByImageId['0'],1);
assert.equal(mapset.walkableByImageId['1'],0);
assert.deepEqual(sourceMapImageAttributes(mapset,0),{imageId:0,walkable:true,haveHeight:false,defence:-1,introDamage:0,outofDamage:0});
assert.deepEqual(sourceMapImageAttributes(mapset,4),{imageId:4,walkable:true,haveHeight:false,defence:-1,introDamage:0,outofDamage:0});
assert.deepEqual(sourceMapImageAttributes(mapset,1),{imageId:1,walkable:false,haveHeight:true,defence:-1,introDamage:0,outofDamage:0});
assert.equal(sourceMapImageAttributes(mapset,999999),null);
const map=JSON.parse(fs.readFileSync('data/generated/stoneage_map_20000.json','utf8'));
const joined=sourceMapTileWithAttributes(map,5,0,mapset);
assert.equal(joined.tile,4500);
assert.equal(joined.attributes?.imageId,4500);
assert.equal(joined.attributes?.walkable,true);
assert.equal(joined.attributes?.defence,-1);
assert.equal(sourceMapTileWithAttributes(map,-1,0,mapset),null);
console.log(JSON.stringify({pass:true,version:'V3.13',focus:'verified mapset image attributes',imageCount:20166,maxImageId:41000,verifiedTileCheck:{floor:20000,x:5,y:0,tile:4500,walkable:true}}));