#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
const j=JSON.parse(fs.readFileSync('data/generated/stoneage_first_idle_route_catalog.json','utf8'));
assert.equal(j.format,'stoneage-first-idle-route-catalog-v1');
assert.equal(j.summary.towns,4);
assert.equal(j.summary.pathClosedTowns,3);
assert.equal(j.summary.sourceBlockedTowns,1);
assert.equal(j.summary.eligibleRouteVariants,8);
assert.equal(j.summary.sourceEligibleRouteVariants,6);
assert.equal(j.summary.productRepairEligibleRouteVariants,2);
const kar=j.routes.find(x=>x.hometown===3);
assert.equal(kar.status,'source_blocked_before_portal');
assert.equal(kar.productRepairId,'karutarna-4000-road-access-v1');
assert.equal(j.productRepairs?.[kar.productRepairId]?.status,'runtime-enabled');
assert.deepEqual(j.productRepairs[kar.productRepairId].portalIds,['4000_to_200_a','4000_to_200_b']);
const jaja=j.routes.find(x=>x.hometown===2);
const blocked=jaja.variants.find(x=>x.portalId==='3000_to_200_b');
assert.deepEqual(blocked.unusableLandingPoints,[[587,318]]);
assert.match(j.policy.productBoundary,/Battle strategy/);
assert.match(j.policy.productBoundary,/offline accrual/);
assert.equal(j.policy.battleStrategy?.mode,'basic_attack_only');
assert.equal(j.policy.battleStrategy?.targetPolicy,'source-default-random');
assert.equal(j.summary.basicBattleStrategyAvailable,true);
console.log(JSON.stringify({pass:true,format:j.format,eligibleRouteVariants:j.summary.eligibleRouteVariants,sourceBlockedTowns:j.summary.sourceBlockedTowns}));
