#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { freshPersistentState } from '../src/stoneage_persistent_state.mjs';
import { dispatchNpcInteraction } from '../src/stoneage_npc_dispatch_runtime.mjs';
import { createFirstRouteRewardHandlers } from '../src/stoneage_first_route_reward_handlers.mjs';
import { createAuditedNpcModuleRegistry } from '../src/stoneage_npc_module_registry_runtime.mjs';
const reachability=JSON.parse(fs.readFileSync('data/generated/stoneage_start_npc_reachability.json','utf8'));
const closure=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_event_closure.json','utf8'));
const audit=JSON.parse(fs.readFileSync('data/generated/stoneage_world_npc_functionset_audit.json','utf8'));
const compatibility=JSON.parse(fs.readFileSync('data/generated/stoneage_changeevent_compatibility_reference.json','utf8'));
const itemRewardCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_item_reward_runtime.json','utf8'));
const itemMakeCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_item_make_runtime.json','utf8'));
const petCatalog=JSON.parse(fs.readFileSync('data/generated/stoneage_new_player_pet_runtime.json','utf8'));
const npc=reachability.rows.find(r=>r.template==='changeevent'&&r.floor===1006&&r.hometown===0);
assert.ok(npc);
const player={floor:1006,x:15,y:21,facingCell:[1006,15,22]};
const strictRegistry=createAuditedNpcModuleRegistry(audit,{modules:{}});
const strictState=freshPersistentState({playerId:'compat-strict'});
const strict=await dispatchNpcInteraction(strictState,npc,player,{interactionRule:'NPC_Util_charIsInFrontOfChar distance=1',moduleRegistry:strictRegistry,runtimeConfig:{compatibilityMode:false,allowExternalCompatibilityAliases:false},transactionId:'strict-1'});
assert.equal(strict.ok,true); assert.equal(strict.handled,false); assert.equal(strict.stage,'module-resolution');
const bundle=createFirstRouteRewardHandlers({itemRewardCatalog,itemMakeCatalog,petCatalog,petIdFactory:(st,created)=>'pet-'+created.petId+'-'+st.pets.petBox.length,itemCapacity:1000,itemCursor:700,randInclusive:(a,b)=>a===b?a:0});
assert.equal(bundle.ok,true);
const runtimeConfig={compatibilityMode:true,allowExternalCompatibilityAliases:true,defaultInteractionAction:'talk',sourceProfile:'fixed-c'};
const compatibilityModule={ExChangeMan:{script:closure.script,kind:'changeevent-compatible'}};
const state=freshPersistentState({playerId:'compat-enabled'}); state.player.level=1; state.player.transmigration=0; state.player.charm=60;
const enabled=await dispatchNpcInteraction(state,npc,player,{interactionRule:'NPC_Util_charIsInFrontOfChar distance=1',moduleRegistry:compatibilityRegistry,handlerFactory:()=>bundle.handlers,transactionId:'compat-1',now:()=> '2026-09-30T11:00:00.000Z'});
assert.equal(enabled.ok,true); assert.equal(enabled.handled,true); assert.equal(enabled.execution.applied,true);
assert.equal(enabled.execution.execution.plan.eventNo,-1);
assert.equal(enabled.state.inventory.itemRuntime.slots['700'].itemId,20145);
assert.equal(enabled.state.inventory.itemRuntime.slots['703'].itemId,18537);
assert.equal(enabled.state.pets.petBox[0].enemyId,341); assert.equal(enabled.state.pets.petBox[0].petId,274);
assert.equal(enabled.state.player.charm,60); assert.equal(enabled.state.events.endWords[11],16384); assert.equal(enabled.state.revision,1);
assert.equal(enabled.execution.save.envelope.format,'stoneage-save-envelope-v1');
console.log(JSON.stringify({pass:true,format:'stoneage-changeevent-browser-compatibility-v1',mapId:1006,npc:'新手接待员',strictModeBlocked:true,compatibilityAlias:'changeevent -> ExChangeMan',interactionGatePassed:true,items:[20145,2849,20228,18537],pet:{enemyId:341,tempNo:274},endEvent:366,charmNoOp:true,savedRevision:1}));
