import assert from 'node:assert/strict';
import fs from 'node:fs';
const game=fs.readFileSync('game.js','utf8');
const html=fs.readFileSync('game.html','utf8');
const readme=fs.readFileSync('README.md','utf8');
const workflow=fs.readFileSync('.github/workflows/v285-battle-false-petskills.yml','utf8');
const pet=JSON.parse(fs.readFileSync('data/generated/stoneage_petskill_runtime.json','utf8'));
const ai=JSON.parse(fs.readFileSync('data/generated/stoneage_enemy_ai.json','utf8'));
assert.doesNotThrow(()=>new Function(game),'game.js syntax');
assert.equal(pet.byId['540'].f,'PETSKILL_Fixitem');
assert.equal(pet.byId['572'].f,'PETSKILL_Inslay');
const used=new Set();
for(const row of Object.values(ai.byEnemyId||{}))for(const id of row?.p||[])if([540,572].includes(Number(id)))used.add(Number(id));
assert.deepEqual([...used].sort((a,b)=>a-b),[540,572]);
const setStart=game.indexOf('const ENEMY_SOURCE_BATTLE_FALSE_SKILL_IDS=new Set([540,572]);');
assert.ok(setStart>=0);
const chooseStart=game.indexOf('function enemyChooseAction');
const chooseEnd=game.indexOf('function enemySignedSkillPercent',chooseStart);
const choose=game.slice(chooseStart,chooseEnd);
assert.ok(choose.includes('ENEMY_SOURCE_BATTLE_FALSE_SKILL_IDS.has(Number(picked.skillId))'));
assert.ok(choose.includes("sourceCWaitReason:'battle-function-precondition-false'"));
const planStart=game.indexOf('function sourcePetRandomSkillPlan');
const planEnd=game.indexOf('function sourcePetChargeSpec',planStart);
const plan=game.slice(planStart,planEnd);
assert.ok(plan.includes('SOURCE_PLAYER_BATTLE_FALSE_PETSKILL_FUNCTIONS'));
assert.ok(plan.includes("PETSKILL_Fixitem"));
assert.ok(plan.includes("PETSKILL_Inslay"));
assert.ok(plan.includes('sourceBattlePreconditionFalse:true'));
assert.ok(plan.indexOf('SOURCE_PLAYER_BATTLE_FALSE_PETSKILL_FUNCTIONS')<plan.indexOf("return {kind:'skill',slot:iNum,skillId,meta,targetDesc};"));
const execStart=game.indexOf('function performEnemyAction');
const execEnd=game.indexOf('function levelCheck',execStart);
const exec=game.slice(execStart,execEnd);
assert.ok(exec.includes('ENEMY_SOURCE_BATTLE_FALSE_SKILL_IDS.has(Number(actor.skillId))'));
assert.ok(exec.includes('sourceBattlePreconditionFalse:true'));
assert.match(html,/PLAYABLE CORE V2\.90/);
assert.match(readme,/PLAYABLE CORE V2\.90/);
assert.ok(readme.includes('V2.85 — Battle-incompatible PETSKILL_Fixitem / PETSKILL_Inslay'));
assert.ok(workflow.includes('node tools/check_v285_battle_false_petskills.mjs'));
console.log(JSON.stringify({pass:true,version:'V2.85',skillIds:[540,572],mode:'exact fixed-C FALSE boundary',enemyAndPlayerPetPaths:true}));