import assert from 'node:assert/strict';
import fs from 'node:fs';
const game=fs.readFileSync('game.js','utf8');
const html=fs.readFileSync('game.html','utf8');
const readme=fs.readFileSync('README.md','utf8');
const workflow=fs.readFileSync('.github/workflows/v283-rideflg-boundary.yml','utf8');
assert.doesNotThrow(()=>new Function(game),'game.js syntax');
const start=game.indexOf('function sourceBattleCommandRideFlag');
const end=game.indexOf('function resetBattleStatuses',start);
assert.ok(start>=0&&end>start);
const fn=game.slice(start,end);
const f=new Function(fn+';return sourceBattleCommandRideFlag;')();
assert.equal(f({petFall:0}),0);
assert.equal(f({petFall:1,foxRound:-1,becomePigSource:0}),-1);
assert.equal(f({petFall:1,foxRound:10,becomePigSource:0}),-2);
assert.equal(f({petFall:1,foxRound:-1,becomePigSource:121}),-3);
assert.equal(f({petFall:1,foxRound:-1,becomePigSource:120}),-1);
assert.equal(game.includes('state.ridePetId=null;'),true);
assert.match(html,/PLAYABLE CORE V2\.90/);
assert.match(readme,/PLAYABLE CORE V2\.90/);
assert.ok(workflow.includes('node tools/check_v283_rideflg_boundary.mjs'));
console.log(JSON.stringify({pass:true,version:'V2.83',rideflg:[0,-1,-2,-3],rideRuntime:'not-enabled'}));