import assert from 'node:assert/strict';
import fs from 'node:fs';
const game=fs.readFileSync('game.js','utf8');
const html=fs.readFileSync('game.html','utf8');
const readme=fs.readFileSync('README.md','utf8');
const workflow=fs.readFileSync('.github/workflows/v284-enemy-vary-roar.yml','utf8');
const pet=JSON.parse(fs.readFileSync('data/generated/stoneage_petskill_runtime.json','utf8'));
const ai=JSON.parse(fs.readFileSync('data/generated/stoneage_enemy_ai.json','utf8'));
assert.doesNotThrow(()=>new Function(game),'game.js syntax');
assert.equal(pet.byId['600'].f,'PETSKILL_Vary');
assert.equal(pet.byId['600'].o,'攻%+30 敏%+30 魔防%-50');
assert.equal(pet.byId['674'].f,'PETSKILL_Vary');
assert.equal(pet.byId['674'].o,'攻%+60 敏%+50 魔防%-80');
assert.equal(pet.byId['734'].f,'PETSKILL_Roar');
assert.equal(pet.byId['734'].o,'1009|1010|1011|989|990|991|992|1030|1031|1032|997|998|999|1000');
const used=new Set();
for(const row of Object.values(ai.byEnemyId||{}))for(const id of row?.p||[])if([600,674,734].includes(Number(id)))used.add(Number(id));
assert.deepEqual([...used].sort((a,b)=>a-b),[600,674,734]);
const prepStart=game.indexOf('function enemyPrepareRoundAction');
const prepEnd=game.indexOf('function battleTargetSnapshot',prepStart);
assert.ok(prepStart>=0&&prepEnd>prepStart);
const prep=game.slice(prepStart,prepEnd);
assert.ok(prep.includes("meta?.f==='PETSKILL_Vary'"));
assert.ok(prep.includes('SOURCE_VARY_WOLF_PETIDS.has'));
assert.ok(prep.includes("enemySignedSkillPercent(meta.o,'攻%')"));
assert.ok(prep.includes("enemySignedSkillPercent(meta.o,'敏%')"));
assert.ok(prep.includes('battlePetVaryStates.set(unit.id'));
assert.ok(prep.includes('workTurn:0'));
assert.ok(prep.includes('persistentVary'));
const advStart=game.indexOf('function sourceAdvanceEnemyVaryTurn');
const advEnd=game.indexOf('function sourcePetPierceFrontEnemy',advStart);
assert.ok(advStart>=0&&advEnd>advStart);
const adv=game.slice(advStart,advEnd);
const map=new Map(); const logs=[];
const advance=new Function('battlePetVaryStates','n','addLog',adv+';return sourceAdvanceEnemyVaryTurn;')(map,v=>Number(v)||0,m=>logs.push(m));
map.set('u',{workTurn:0,attackPct:30,dexPct:30});
for(let i=1;i<=5;i++){const r=advance({id:'u',name:'敵狼人'});assert.equal(r.workTurn,i);assert.equal(r.expired,false);}
const expired=advance({id:'u',name:'敵狼人'});
assert.equal(expired.expired,true);
assert.equal(map.has('u'),false);
const actStart=game.indexOf('function performEnemyAction');
const actEnd=game.indexOf('function levelCheck',actStart);
const action=game.slice(actStart,actEnd);
assert.ok(action.includes("meta?.f==='PETSKILL_Roar'"));
assert.ok(action.includes('performEnemyRoar(actor,unit,options,meta)'));
assert.ok(action.includes("meta?.f==='PETSKILL_Vary'"));
assert.equal(action.includes('unsupported:true'),false);
const roarStart=game.indexOf('function performEnemyRoar');
const roarEnd=game.indexOf('function performEnemyAction',roarStart);
const roar=game.slice(roarStart,roarEnd);
assert.ok(roar.includes('fixed BATTLE_S_Roar'));
assert.ok(roar.includes('battlePetOutIds.add(pet.id)'));
assert.ok(roar.includes('sourceClearPetVary(pet)'));
assert.ok(roar.includes('sourcePetRoarPetIds(meta)'));
assert.ok(roar.includes('noDamage:true'));
assert.match(html,/PLAYABLE CORE V2\.84/);
assert.match(readme,/PLAYABLE CORE V2\.84/);
assert.ok(workflow.includes('node tools/check_v284_enemy_vary_roar.mjs'));
console.log(JSON.stringify({pass:true,version:'V2.84',focus:'Enemy PETSKILL_Vary 600/674 + PETSKILL_Roar 734 source parity',varyPetIds:[981,982,983,984],varyTurns:5,roarTarget:'player-pet-only',roarNoDamage:true}));